MSEC-49: Create an sdk to access that logging api

diff --git a/.azure/nuget-package.yml b/.azure/nuget-package.yml
--- a/.azure/nuget-package.yml
+++ b/.azure/nuget-package.yml
@@ -26,9 +26,18 @@ parameters:
     # Note: Should only be used once for the initial versioning.
 
 variables:
-  solution: '**/*.sln'
-  buildPlatform: 'Any CPU'
-  buildConfiguration: 'Release'
+- group: nuget-pipeline-secrets
+
+# Define other variables separately
+- name: solution
+  value: '**/*.sln'
+- name: buildPlatform
+  value: 'Any CPU'
+- name: buildConfiguration
+  value: 'Release'
+- name: packageIds
+  value: |
+    MeraStore.Service.Logging.SDK: '27cd53d6-f25f-4b9c-8300-bab447ac79f9'
 
 jobs:
 - job: BuildAndTest
@@ -81,6 +90,7 @@ jobs:
         #!/bin/bash
 
         echo "Starting version calculation..."
+        echo "Using the secret: $(System.AccessToken)"
 
         # Get version type from parameters
         versionType="${{ parameters.versionType }}"
@@ -89,15 +99,27 @@ jobs:
         echo "Version type selected: $versionType"
         echo "Project selected: $projectName"
 
+        # Get the package ID for the selected project
+        packageIds=$(echo "${{ variables.packageIds }}")
+        packageId=$(echo "$packageIds" | grep -oP "(?<=${projectName}: ').*?(?=')")
+
+        if [[ -z "$packageId" ]]; then
+            echo "Error: Package ID for project '$projectName' not found."
+            exit 1
+        fi
+
         if [[ "$versionType" != "New" ]]; then
             # Fetch the latest version from NuGet feed
-            nugetSource="https://pkgs.dev.azure.com/sanjyotagureddy/merastore/_packaging/mera-store/nuget/v3/index.json"
-            packageName="MeraStore.Service.Logging.SDK"
+            nugetSource="https://feeds.dev.azure.com/sanjyotagureddy/merastore/_apis/packaging/Feeds/merastore/Packages/$packageId"
 
-            echo "Fetching the latest version for package: $packageName from $nugetSource"
+            echo "Fetching the latest version for package ID: $packageId from $nugetSource"
+            response=$(curl -s -H "Authorization: Basic $AZURE_PATH" "$nugetSource")
             
             # Get the latest version using NuGet API
-            latestVersion=$(curl -s "$nugetSource" | jq -r '.data[] | select(.id=="'"$packageName"'") | .version' | sort -V | tail -n 1)
+            latestVersion=$(echo "$response" | jq -r '.versions[] | select(.isLatest==true) | .version')
+            echo $latestVersion
+            # Print the raw response for debugging
+            echo "Raw response: $response"
 
             # Default to 1.0.0 if no latest version is found
             if [[ -z "$latestVersion" ]]; then
@@ -158,6 +180,7 @@ jobs:
         # Set the calculated version as a pipeline name
         echo "##vso[build.updatebuildnumber]$projectName-$version"
       displayName: 'Calculate Version Number'
+
     - task: DotNetCoreCLI@2
       displayName: DotNet Pack
       inputs:
